amazon.accessKey=${AMAZON_ACCESS_KEY}
amazon.secretKey=${AMAZON_SECRET_KEY}
backend.user=${BACKEND_USER}
backend.password=${BACKEND_PASSWORD}
backend.token=${BACKEND_API_KEY}
backend.jtw.token=${BACKEND_JWT_TOKEN}